# SPDX-FileCopyrightText: 2024 The Forkbomb Company
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Deploy and Release
on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  pages: write
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  attestations: write

jobs:
  deploy:
    environment:
      name: Demo
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: bun install
      - run: bun add -g semantic-release
      - run: bun add -D @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/git @semantic-release/github
      - name: Calculate release version
        run: |
          VERSION=$(npx semantic-release --dry-run --no-ci | grep -Po '(?<=The next release version is ).*')
          echo "$VERSION" > VERSION
      - run: bun run build
      - run: cp dist/index.html pqspread.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: pqspread.html
      - uses: actions/deploy-pages@v4
        id: deployment
      - run: semantic-release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
